### ISSUE TITLE
Quick add text box is not focused on open

### ISSUE THREAD

**Issue by jaynavar** [timediv/QuickDynalist#13]
After the latest update the quick add text box is no longer focused when the dialog box is first opened (i.e. flashing cursor in the text box). This does not present issues normally as inputting text from the keyboard initiates focus and still works as expected, however extensibility/automation plugins like Tasker's AutoInput can no longer place text into the text box.

To repro the issue, just open up Quick Dynalist and you'll see that there is no cursor in the textbox. Now start typing text and then delete the text. You'll see that the cursor is now present even though there is no text, which is the state the dialog box should also enter on open.

After realizing that my Tasker task was broken, I verified that entering text then removing it (so that the text box now had the flashing cursor) allowed AutoInput to properly fill in the text field.

**Comment by louiskirsch** [comment]
Interesting. I'm not sure what produced this issue.

**Comment by louiskirsch** [comment]
Fixed in b2aa3ffc14fe1d95180e485985db87467bac376b
