### ISSUE TITLE
"Detect and highlight possible tags" setting disable not working

### ISSUE THREAD

**Issue by jaynavar** [timediv/QuickDynalist#15]
As of the latest update, the auto-highlighting of tags after "#" and "@" has been occurring even with the setting disabled. I tried toggling the setting, and it still wouldn't disable the feature.

**Comment by louiskirsch** [comment]
Thank you for the report.
Restarting the app applies the setting. I will have to make sure the setting is updated whenever an activity regains focus.

**Comment by jaynavar** [comment]
Even after restarting the app the setting is not taking effect.

**Comment by louiskirsch** [comment]
Just to make sure we are talking about the right effect: The setting applies only to the auto highlighting in the edit text, i.e. when you type 'todo' and there is a tag '#todo' it is automatically applied. When typing '#todo' the tag is ALWAYS highlighted.

**Comment by jaynavar** [comment]
Oh I see. I was assuming the setting disabled all highlighting.
