### ISSUE TITLE
Feature request: add anchor text for URL sharing similarly to Dynalist app functionality

### ISSUE THREAD

**Issue by ajvsol** [timediv/QuickDynalist#2]
When you share URLs from your web browser with the Dynalist app it creates anchor text (using the page title), whereas sharing with Quick Dynalist only adds the raw URL.

**Comment by louiskirsch** [comment]
Thanks for this feature request, we will include it in a future version.

**Comment by louiskirsch** [comment]
Implemented in version 1.5
