### ISSUE TITLE
App appears in "Recent Apps" when just used for "Quick dialog"

### ISSUE THREAD

**Issue by jaynavar** [timediv/QuickDynalist#5]
I often click on the app from my home screen just to add a new item to my inbox and then press "ADD & CLOSE", however the app still appears in my "Recent Apps" list. This is not ideal as my intention is just to use it as a widget essentially, and I'd rather not have to go into my recent apps and clear it away.

There is a way to configure it in Android so that the app doesn't appear in "Recent Apps", however I also understand the use case for wanting it in "Recent Apps" when you use the "Item list" view, so I'm thinking you only want it to hide from recent apps if the app was opened in "Quick dialog" view. Another thing to consider is that disabling from recent apps might prevent background sync, although I don't think this is the case as my workaround still works fine for background sync/offline recovery sync (see footnote regarding Tasker workaround).

Would be interested in hearing your thoughts on this and whether you think it's a good idea and feasible to implement!

(FYI, in the meantime I'm using a Tasker wrapper Task that launches Quick Dynalist while preventing it from appearing in recent apps ([link](https://tasker.joaoapps.com/userguide/en/help/ah_load_app.html)), but I'd much prefer native support for the feature)

Developer references below:
https://developer.android.com/guide/components/activities/recents#removing
https://developer.android.com/guide/topics/manifest/activity-element#exclude

**Comment by louiskirsch** [comment]
I will implement this as discussed in https://github.com/timediv/QuickDynalist/pull/7

**Comment by jaynavar** [comment]
Does 384cbeda88fe40b207bb4cc8ca318ce2509efb2c fix this issue?

**Comment by louiskirsch** [comment]
Yes

**Comment by jaynavar** [comment]
Based on the code, it looks like this only clears the task if you specifically click on the "ADD & CLOSE" button, but what about the case where you just click focus away from the quick dialog box? I would think that in this case you also don't want the app to appear in recent apps, but I don't think this is handled with the current code.

Do you know if you can create an event listener for this "defocus" event so you can trigger the `finish()` function in this case as well?

**Comment by jaynavar** [comment]
It looks like you can set an `onCancel` listener for the dialog box: https://stackoverflow.com/questions/9516287/how-do-i-fire-an-event-when-click-occurs-outside-a-dialog

**Comment by jaynavar** [comment]
Actually `onDismiss` seems more appropriate: https://developer.android.com/reference/android/content/DialogInterface.OnDismissListener

**Comment by louiskirsch** [comment]
This doesn't work for activities. But clicking outside of the window calls finish, which is overridden to clear the task. I tested it, works fine.

**Comment by jaynavar** [comment]
Perfect! Thanks for following up 😃, I'll close the issue.

I'm really excited to test out the new version, looks like there's been tons of new features since 1.11 based on the commit history! When do you plan on posting the next release on the Google Play Store? 

Thanks for all of your work on this awesome app!

**Comment by louiskirsch** [comment]
The new version is already in the play store as a beta. You are welcome to join the beta program. Unfortunately we are still missing an API change that makes the version truly stable.

**Comment by jaynavar** [comment]
Awesome! Just joined the beta and the "Recent Apps" behavior is working perfectly!

However, it doesn't look like the autocorrect issue has been fixed. Do you know if that change was built into this version?

**Comment by louiskirsch** [comment]
Yes it should be there, you can check the code.

**Comment by jaynavar** [comment]
Yes, I see it in the code. However, it does not appear to be working (at least on my device). I'm reopening #3 since it doesn't appear to be fixed (we can move further conversation there).

As stated in PR #6, I wasn't able to test out the change myself since I don't have an active android development environment. Were you able to verify the behavior change before (or after) the PR merged?
