### ISSUE TITLE
Removing "#primary #inbox" tags does not re-add Inbox

### ISSUE THREAD

**Issue by jaynavar** [timediv/QuickDynalist#9]
**Steps to reproduce:**

1. Go to your inbox in Dynalist, and add the tags "#primary #inbox" to the inbox item
1. "Sync now" in Quick Dynalist so that it no longer shows default inbox but now shows your primary inbox
1. Go to your inbox item and remove the "#primary #inbox" tags from the item
1. "Sync now" in Quick Dynalist

**Expected behavior:**

Quick Dynalist goes back to state before you added the "#primary #inbox" tags, namely that it just has a generic "Inbox" list with the default logo.

**Actual behavior:**

The generic "Inbox" item does not reappear, even though the original item is still set as the inbox in Dynalist. In order to fix the issue I had to clear app data and re-setup the app. Even setting inbox to a different item in Dynalist does not trigger the "Inbox" to be re-added.

**Comment by louiskirsch** [comment]
Thank you, I will have a look at this.
